# Generated by Django 6.0.4 on 2026-04-25 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_performancerecommendation_performancerecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancerecommendation",
            name="created_by",
        ),
        migrations.AddField(
            model_name="performancerecommendation",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
